version: "3"

services:
  sr-velocity:
    container_name: sr-velocity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
